package B4A.GPS.PaiNaiMa;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class gpsmodule {
private static gpsmodule mostCurrent = new gpsmodule();
public static Object getObject() {
    throw new RuntimeException("Code module does not support this method.");
}
 public anywheresoftware.b4a.keywords.Common __c = null;
public B4A.GPS.PaiNaiMa.main _main = null;
public B4A.GPS.PaiNaiMa.satellites _satellites = null;
public B4A.GPS.PaiNaiMa.setup _setup = null;
public B4A.GPS.PaiNaiMa.gpspaths _gpspaths = null;
public B4A.GPS.PaiNaiMa.gpssave _gpssave = null;
public static String  _loadpath(anywheresoftware.b4a.BA _ba) throws Exception{
anywheresoftware.b4a.randomaccessfile.RandomAccessFile _randomfile = null;
B4A.GPS.PaiNaiMa.main._gpslocation _loc = null;
 //BA.debugLineNum = 9;BA.debugLine="Sub LoadPath";
 //BA.debugLineNum = 10;BA.debugLine="Dim RandomFile As RandomAccessFile";
_randomfile = new anywheresoftware.b4a.randomaccessfile.RandomAccessFile();
 //BA.debugLineNum = 12;BA.debugLine="Main.GPSPath.Initialize";
mostCurrent._main._gpspath.Initialize();
 //BA.debugLineNum = 13;BA.debugLine="RandomFile.Initialize(Main.GPSDir, Main.GPSPathFi";
_randomfile.Initialize(mostCurrent._main._gpsdir,mostCurrent._main._gpspathfilename,anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 14;BA.debugLine="Main.GPSPathComment = RandomFile.ReadObject(Rando";
mostCurrent._main._gpspathcomment = BA.ObjectToString(_randomfile.ReadObject(_randomfile.CurrentPosition));
 //BA.debugLineNum = 15;BA.debugLine="Main.GPSPath = RandomFile.ReadObject(RandomFile.C";
mostCurrent._main._gpspath.setObject((java.util.List)(_randomfile.ReadObject(_randomfile.CurrentPosition)));
 //BA.debugLineNum = 16;BA.debugLine="RandomFile.Close";
_randomfile.Close();
 //BA.debugLineNum = 17;BA.debugLine="Dim loc As GPSLocation";
_loc = new B4A.GPS.PaiNaiMa.main._gpslocation();
 //BA.debugLineNum = 18;BA.debugLine="loc = Main.GPSPath.Get(0)";
_loc = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (0)));
 //BA.debugLineNum = 19;BA.debugLine="Main.GPSPathTime0 = loc.Time";
mostCurrent._main._gpspathtime0 = _loc.Time;
 //BA.debugLineNum = 20;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
public static String  _savekmlline(anywheresoftware.b4a.BA _ba,int _linewidth,long _linecolor,boolean _dispstartpoint,String _startpointtext,boolean _dispendpoint,String _endpointtext) throws Exception{
int _i = 0;
String _txt = "";
B4A.GPS.PaiNaiMa.main._gpslocation _loc1 = null;
B4A.GPS.PaiNaiMa.main._gpslocation _loc2 = null;
String _tab2 = "";
String _tab3 = "";
String _tab4 = "";
String _tab5 = "";
String _tab6 = "";
byte[] _bytes = null;
anywheresoftware.b4a.agraham.byteconverter.ByteConverter _bc = null;
long[] _cols = null;
String _col = "";
String _col1 = "";
anywheresoftware.b4a.objects.streams.File.TextWriterWrapper _tw = null;
 //BA.debugLineNum = 31;BA.debugLine="Sub SaveKMLLine(LineWidth As Int, LineColor As Lon";
 //BA.debugLineNum = 32;BA.debugLine="Dim i As Int";
_i = 0;
 //BA.debugLineNum = 33;BA.debugLine="Dim txt As String";
_txt = "";
 //BA.debugLineNum = 34;BA.debugLine="Dim loc1, loc2 As GPSLocation";
_loc1 = new B4A.GPS.PaiNaiMa.main._gpslocation();
_loc2 = new B4A.GPS.PaiNaiMa.main._gpslocation();
 //BA.debugLineNum = 35;BA.debugLine="Dim TAB2, TAB3, TAB4, TAB5, TAB6 As String";
_tab2 = "";
_tab3 = "";
_tab4 = "";
_tab5 = "";
_tab6 = "";
 //BA.debugLineNum = 37;BA.debugLine="TAB2 = TAB & TAB";
_tab2 = anywheresoftware.b4a.keywords.Common.TAB+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 38;BA.debugLine="TAB3 = TAB2 & TAB";
_tab3 = _tab2+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 39;BA.debugLine="TAB4 = TAB3 & TAB";
_tab4 = _tab3+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 40;BA.debugLine="TAB5 = TAB4 & TAB";
_tab5 = _tab4+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 41;BA.debugLine="TAB6 = TAB5 & TAB";
_tab6 = _tab5+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 43;BA.debugLine="loc1 = Main.GPSPath.Get(0)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (0)));
 //BA.debugLineNum = 44;BA.debugLine="loc2 = Main.GPSPath.Get(Main.GPSPath.Size - 1)";
_loc2 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (mostCurrent._main._gpspath.getSize()-1)));
 //BA.debugLineNum = 46;BA.debugLine="txt = \"<?xml version='1.0' encoding='UTF-8'?>\" &";
_txt = "<?xml version='1.0' encoding='UTF-8'?>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 47;BA.debugLine="txt = txt & \"<kml xmlns='http://earth.google.com/";
_txt = _txt+"<kml xmlns='http://earth.google.com/kml/2.2'>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 49;BA.debugLine="txt = txt & TAB & \"<Folder>\" & CRLF";
_txt = _txt+anywheresoftware.b4a.keywords.Common.TAB+"<Folder>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 51;BA.debugLine="If DispStartPoint = True Then";
if (_dispstartpoint==anywheresoftware.b4a.keywords.Common.True) { 
 //BA.debugLineNum = 52;BA.debugLine="txt = txt & TAB2 & \"<Placemark>\" & CRLF";
_txt = _txt+_tab2+"<Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 53;BA.debugLine="txt = txt & TAB3 & \"<name>\" & StartPointText & \"";
_txt = _txt+_tab3+"<name>"+_startpointtext+"</name>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 54;BA.debugLine="txt = txt & TAB3 & \"<Style>\" & CRLF";
_txt = _txt+_tab3+"<Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 55;BA.debugLine="txt = txt & TAB4 & \"<IconStyle>\" & CRLF";
_txt = _txt+_tab4+"<IconStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 56;BA.debugLine="txt = txt & TAB5 & \"<Icon>\" & CRLF";
_txt = _txt+_tab5+"<Icon>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 57;BA.debugLine="txt = txt & TAB6 & \"<href>http://maps.google.com";
_txt = _txt+_tab6+"<href>http://maps.google.com/mapfiles/kml/pushpin/grn-pushpin.png</href>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 58;BA.debugLine="txt = txt & TAB5 & \"</Icon>\" & CRLF";
_txt = _txt+_tab5+"</Icon>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 59;BA.debugLine="txt = txt & TAB4 & \"</IconStyle>\" & CRLF";
_txt = _txt+_tab4+"</IconStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 60;BA.debugLine="txt = txt & TAB3 & \"</Style>\" & CRLF";
_txt = _txt+_tab3+"</Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 61;BA.debugLine="txt = txt & TAB3 & \"<Point>\" & CRLF";
_txt = _txt+_tab3+"<Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 62;BA.debugLine="txt = txt & TAB4 & \"<coordinates>\" & CRLF";
_txt = _txt+_tab4+"<coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 63;BA.debugLine="loc1 = Main.GPSPath.Get(0)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (0)));
 //BA.debugLineNum = 64;BA.debugLine="txt = txt & TAB5 & loc1.Longitude & \",\" & loc1.L";
_txt = _txt+_tab5+BA.NumberToString(_loc1.Longitude)+","+BA.NumberToString(_loc1.Latitude)+","+BA.NumberToString(_loc1.Altitude)+" "+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 65;BA.debugLine="txt = txt & TAB4 & \"</coordinates>\" & CRLF";
_txt = _txt+_tab4+"</coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 66;BA.debugLine="txt = txt & TAB3 & \"</Point>\" & CRLF";
_txt = _txt+_tab3+"</Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 67;BA.debugLine="txt = txt & TAB2 & \"</Placemark>\" & CRLF";
_txt = _txt+_tab2+"</Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 70;BA.debugLine="If DispEndPoint = True Then";
if (_dispendpoint==anywheresoftware.b4a.keywords.Common.True) { 
 //BA.debugLineNum = 71;BA.debugLine="txt = txt & TAB2 & \"<Placemark>\" & CRLF";
_txt = _txt+_tab2+"<Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 72;BA.debugLine="txt = txt & TAB3 & \"<name>\" & EndPointText & \"</";
_txt = _txt+_tab3+"<name>"+_endpointtext+"</name>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 73;BA.debugLine="txt = txt & TAB3 & \"<Style>\" & CRLF";
_txt = _txt+_tab3+"<Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 74;BA.debugLine="txt = txt & TAB4 & \"<IconStyle>\" & CRLF";
_txt = _txt+_tab4+"<IconStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 75;BA.debugLine="txt = txt & TAB5 & \"<Icon>\" & CRLF";
_txt = _txt+_tab5+"<Icon>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 76;BA.debugLine="txt = txt & TAB6 & \"<href>http://maps.google.com";
_txt = _txt+_tab6+"<href>http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png</href>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 77;BA.debugLine="txt = txt & TAB5 & \"</Icon>\" & CRLF";
_txt = _txt+_tab5+"</Icon>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 78;BA.debugLine="txt = txt & TAB4 & \"</IconStyle>\" & CRLF";
_txt = _txt+_tab4+"</IconStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 79;BA.debugLine="txt = txt & TAB3 & \"</Style>\" & CRLF";
_txt = _txt+_tab3+"</Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 80;BA.debugLine="txt = txt & TAB3 & \"<Point>\" & CRLF";
_txt = _txt+_tab3+"<Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 81;BA.debugLine="txt = txt & TAB4 & \"<coordinates>\" & CRLF";
_txt = _txt+_tab4+"<coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 82;BA.debugLine="loc1 = Main.GPSPath.Get(Main.GPSPath.Size - 1)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (mostCurrent._main._gpspath.getSize()-1)));
 //BA.debugLineNum = 83;BA.debugLine="txt = txt & TAB5 & loc1.Longitude & \",\" & loc1.L";
_txt = _txt+_tab5+BA.NumberToString(_loc1.Longitude)+","+BA.NumberToString(_loc1.Latitude)+","+BA.NumberToString(_loc1.Altitude)+" "+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 84;BA.debugLine="txt = txt & TAB4 & \"</coordinates>\" & CRLF";
_txt = _txt+_tab4+"</coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 85;BA.debugLine="txt = txt & TAB3 & \"</Point>\" & CRLF";
_txt = _txt+_tab3+"</Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 86;BA.debugLine="txt = txt & TAB2 & \"</Placemark>\" & CRLF";
_txt = _txt+_tab2+"</Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 89;BA.debugLine="txt = txt & TAB2 & \"<Placemark>\" & CRLF";
_txt = _txt+_tab2+"<Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 90;BA.debugLine="txt = txt & TAB3 & \"<name>\" & Main.GPSPathFilenam";
_txt = _txt+_tab3+"<name>"+mostCurrent._main._gpspathfilenamekml+"</name>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 91;BA.debugLine="txt = txt & TAB4 & \"<description>\" & CRLF";
_txt = _txt+_tab4+"<description>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 92;BA.debugLine="If Main.GPSPathComment<>\"\" Then";
if ((mostCurrent._main._gpspathcomment).equals("") == false) { 
 //BA.debugLineNum = 93;BA.debugLine="txt = txt & TAB4 & Main.GPSPathComment & CRLF";
_txt = _txt+_tab4+mostCurrent._main._gpspathcomment+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 95;BA.debugLine="If loc1.Time > 0 Then";
if (_loc1.Time>0) { 
 //BA.debugLineNum = 96;BA.debugLine="txt = txt & TAB4 & \"Date: \" & DateTime.Date(loc1";
_txt = _txt+_tab4+"Date: "+anywheresoftware.b4a.keywords.Common.DateTime.Date(_loc1.Time)+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 97;BA.debugLine="txt = txt & TAB4 & \"Start Time: \" & DateTime.Tim";
_txt = _txt+_tab4+"Start Time: "+anywheresoftware.b4a.keywords.Common.DateTime.Time(_loc1.Time)+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 98;BA.debugLine="txt = txt & TAB4 & \"End Time: \" & DateTime.Time(";
_txt = _txt+_tab4+"End Time: "+anywheresoftware.b4a.keywords.Common.DateTime.Time(_loc2.Time)+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 100;BA.debugLine="txt = txt & TAB3 & \"</description>\" & CRLF";
_txt = _txt+_tab3+"</description>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 101;BA.debugLine="txt = txt & TAB3 & \"<Style>\" & CRLF";
_txt = _txt+_tab3+"<Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 102;BA.debugLine="txt = txt & TAB4 & \"<LineStyle>\" & CRLF";
_txt = _txt+_tab4+"<LineStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 107;BA.debugLine="Dim bytes() As Byte";
_bytes = new byte[(int) (0)];
;
 //BA.debugLineNum = 108;BA.debugLine="Dim bc As ByteConverter";
_bc = new anywheresoftware.b4a.agraham.byteconverter.ByteConverter();
 //BA.debugLineNum = 109;BA.debugLine="Dim cols(1) As Long";
_cols = new long[(int) (1)];
;
 //BA.debugLineNum = 110;BA.debugLine="Dim col, col1 As String";
_col = "";
_col1 = "";
 //BA.debugLineNum = 111;BA.debugLine="cols(0) = LineColor";
_cols[(int) (0)] = _linecolor;
 //BA.debugLineNum = 112;BA.debugLine="bytes = bc.LongsToBytes(cols)		' convert Long to";
_bytes = _bc.LongsToBytes(_cols);
 //BA.debugLineNum = 113;BA.debugLine="col = bc.HexFromBytes(bytes)		' color in hex, con";
_col = _bc.HexFromBytes(_bytes);
 //BA.debugLineNum = 114;BA.debugLine="col = col.SubString2(col.Length - 8, col.Length)";
_col = _col.substring((int) (_col.length()-8),_col.length());
 //BA.debugLineNum = 115;BA.debugLine="col = col.ToLowerCase";
_col = _col.toLowerCase();
 //BA.debugLineNum = 117;BA.debugLine="col1 = col.SubString2(0, 2) & col.SubString2(6, 8";
_col1 = _col.substring((int) (0),(int) (2))+_col.substring((int) (6),(int) (8))+_col.substring((int) (4),(int) (6))+_col.substring((int) (2),(int) (4));
 //BA.debugLineNum = 118;BA.debugLine="txt = txt & TAB5 & \"<color>\" & col1 & \"</color>\"";
_txt = _txt+_tab5+"<color>"+_col1+"</color>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 119;BA.debugLine="txt = txt & TAB5 & \"<width>\" & LineWidth & \"</wid";
_txt = _txt+_tab5+"<width>"+BA.NumberToString(_linewidth)+"</width>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 120;BA.debugLine="txt = txt & TAB4 & \"</LineStyle>\" & CRLF";
_txt = _txt+_tab4+"</LineStyle>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 121;BA.debugLine="txt = txt & TAB3 & \"</Style>\" & CRLF";
_txt = _txt+_tab3+"</Style>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 122;BA.debugLine="txt = txt & TAB3 & \"<LineString>\" & CRLF";
_txt = _txt+_tab3+"<LineString>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 123;BA.debugLine="txt = txt & TAB4 & \"<coordinates>\" & CRLF";
_txt = _txt+_tab4+"<coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 125;BA.debugLine="txt = txt & TAB4";
_txt = _txt+_tab4;
 //BA.debugLineNum = 126;BA.debugLine="For i = 0 To Main.GPSPath.Size - 1";
{
final int step82 = 1;
final int limit82 = (int) (mostCurrent._main._gpspath.getSize()-1);
for (_i = (int) (0) ; (step82 > 0 && _i <= limit82) || (step82 < 0 && _i >= limit82); _i = ((int)(0 + _i + step82)) ) {
 //BA.debugLineNum = 127;BA.debugLine="loc1 = Main.GPSPath.Get(i)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get(_i));
 //BA.debugLineNum = 128;BA.debugLine="txt = txt & loc1.Longitude & \",\" & loc1.Latitude";
_txt = _txt+BA.NumberToString(_loc1.Longitude)+","+BA.NumberToString(_loc1.Latitude)+","+BA.NumberToString(_loc1.Altitude)+" ";
 }
};
 //BA.debugLineNum = 130;BA.debugLine="txt = txt & CRLF & TAB4 & \"</coordinates>\" & CRLF";
_txt = _txt+anywheresoftware.b4a.keywords.Common.CRLF+_tab4+"</coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 131;BA.debugLine="txt = txt & TAB3 & \"</LineString>\" & CRLF";
_txt = _txt+_tab3+"</LineString>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 132;BA.debugLine="txt = txt & TAB2 & \"</Placemark>\" & CRLF";
_txt = _txt+_tab2+"</Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 134;BA.debugLine="txt = txt & TAB & \"</Folder>\" & CRLF";
_txt = _txt+anywheresoftware.b4a.keywords.Common.TAB+"</Folder>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 136;BA.debugLine="txt = txt & \"</kml>\"";
_txt = _txt+"</kml>";
 //BA.debugLineNum = 138;BA.debugLine="Dim tw As TextWriter";
_tw = new anywheresoftware.b4a.objects.streams.File.TextWriterWrapper();
 //BA.debugLineNum = 140;BA.debugLine="tw.Initialize(File.OpenOutput(Main.GPSDir, Main.G";
_tw.Initialize((java.io.OutputStream)(anywheresoftware.b4a.keywords.Common.File.OpenOutput(mostCurrent._main._gpsdir,mostCurrent._main._gpspathfilenamekml,anywheresoftware.b4a.keywords.Common.False).getObject()));
 //BA.debugLineNum = 141;BA.debugLine="tw.Write(txt)";
_tw.Write(_txt);
 //BA.debugLineNum = 142;BA.debugLine="tw.Close";
_tw.Close();
 //BA.debugLineNum = 143;BA.debugLine="End Sub";
return "";
}
public static String  _savekmlpoint(anywheresoftware.b4a.BA _ba) throws Exception{
String _txt = "";
B4A.GPS.PaiNaiMa.main._gpslocation _loc1 = null;
String _tab2 = "";
String _tab3 = "";
String _tab4 = "";
String _tab5 = "";
String _tab6 = "";
anywheresoftware.b4a.objects.streams.File.TextWriterWrapper _tw = null;
 //BA.debugLineNum = 145;BA.debugLine="Sub SaveKMLPoint";
 //BA.debugLineNum = 146;BA.debugLine="Dim txt As String";
_txt = "";
 //BA.debugLineNum = 147;BA.debugLine="Dim loc1 As GPSLocation";
_loc1 = new B4A.GPS.PaiNaiMa.main._gpslocation();
 //BA.debugLineNum = 148;BA.debugLine="Dim TAB2, TAB3, TAB4, TAB5, TAB6 As String";
_tab2 = "";
_tab3 = "";
_tab4 = "";
_tab5 = "";
_tab6 = "";
 //BA.debugLineNum = 150;BA.debugLine="TAB2 = TAB & TAB";
_tab2 = anywheresoftware.b4a.keywords.Common.TAB+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 151;BA.debugLine="TAB3 = TAB2 & TAB";
_tab3 = _tab2+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 152;BA.debugLine="TAB4 = TAB3 & TAB";
_tab4 = _tab3+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 153;BA.debugLine="TAB5 = TAB4 & TAB";
_tab5 = _tab4+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 154;BA.debugLine="TAB6 = TAB5 & TAB";
_tab6 = _tab5+anywheresoftware.b4a.keywords.Common.TAB;
 //BA.debugLineNum = 156;BA.debugLine="loc1 = Main.GPSPath.Get(0)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (0)));
 //BA.debugLineNum = 158;BA.debugLine="txt = \"<?xml version='1.0' encoding='UTF-8'?>\" &";
_txt = "<?xml version='1.0' encoding='UTF-8'?>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 159;BA.debugLine="txt = txt & \"<kml xmlns='http://earth.google.com/";
_txt = _txt+"<kml xmlns='http://earth.google.com/kml/2.2'>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 161;BA.debugLine="txt = txt & TAB & \"<Placemark>\" & CRLF";
_txt = _txt+anywheresoftware.b4a.keywords.Common.TAB+"<Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 162;BA.debugLine="txt = txt & TAB2 & \"<name>\" & Main.GPSPathFilenam";
_txt = _txt+_tab2+"<name>"+mostCurrent._main._gpspathfilenamekml+"</name>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 163;BA.debugLine="txt = txt & TAB2 & \"<description>\" & CRLF";
_txt = _txt+_tab2+"<description>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 164;BA.debugLine="If Main.GPSPathComment<>\"\" Then";
if ((mostCurrent._main._gpspathcomment).equals("") == false) { 
 //BA.debugLineNum = 165;BA.debugLine="txt = txt & TAB3 & Main.GPSPathComment & CRLF";
_txt = _txt+_tab3+mostCurrent._main._gpspathcomment+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 167;BA.debugLine="If loc1.Time > 0 Then";
if (_loc1.Time>0) { 
 //BA.debugLineNum = 168;BA.debugLine="txt = txt & TAB3 & \"Date: \" & DateTime.Date(loc1";
_txt = _txt+_tab3+"Date: "+anywheresoftware.b4a.keywords.Common.DateTime.Date(_loc1.Time)+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 169;BA.debugLine="txt = txt & TAB3 & \"Time: \" & DateTime.Time(loc1";
_txt = _txt+_tab3+"Time: "+anywheresoftware.b4a.keywords.Common.DateTime.Time(_loc1.Time)+anywheresoftware.b4a.keywords.Common.CRLF;
 };
 //BA.debugLineNum = 171;BA.debugLine="txt = txt & TAB2 & \"</description>\" & CRLF";
_txt = _txt+_tab2+"</description>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 173;BA.debugLine="txt = txt & TAB2 & \"<Point>\" & CRLF";
_txt = _txt+_tab2+"<Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 174;BA.debugLine="txt = txt & TAB3 & \"<coordinates>\" & CRLF";
_txt = _txt+_tab3+"<coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 175;BA.debugLine="loc1 = Main.GPSPath.Get(0)";
_loc1 = (B4A.GPS.PaiNaiMa.main._gpslocation)(mostCurrent._main._gpspath.Get((int) (0)));
 //BA.debugLineNum = 176;BA.debugLine="txt = txt & TAB4 & loc1.Longitude & \",\" & loc1.La";
_txt = _txt+_tab4+BA.NumberToString(_loc1.Longitude)+","+BA.NumberToString(_loc1.Latitude)+","+BA.NumberToString(_loc1.Altitude)+" "+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 177;BA.debugLine="txt = txt & TAB3 & \"</coordinates>\" & CRLF";
_txt = _txt+_tab3+"</coordinates>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 178;BA.debugLine="txt = txt & TAB2 & \"</Point>\" & CRLF";
_txt = _txt+_tab2+"</Point>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 179;BA.debugLine="txt = txt & TAB & \"</Placemark>\" & CRLF";
_txt = _txt+anywheresoftware.b4a.keywords.Common.TAB+"</Placemark>"+anywheresoftware.b4a.keywords.Common.CRLF;
 //BA.debugLineNum = 180;BA.debugLine="txt = txt & \"</kml>\"";
_txt = _txt+"</kml>";
 //BA.debugLineNum = 182;BA.debugLine="Dim tw As TextWriter";
_tw = new anywheresoftware.b4a.objects.streams.File.TextWriterWrapper();
 //BA.debugLineNum = 184;BA.debugLine="tw.Initialize(File.OpenOutput(Main.GPSDir, Main.G";
_tw.Initialize((java.io.OutputStream)(anywheresoftware.b4a.keywords.Common.File.OpenOutput(mostCurrent._main._gpsdir,mostCurrent._main._gpspathfilenamekml,anywheresoftware.b4a.keywords.Common.False).getObject()));
 //BA.debugLineNum = 185;BA.debugLine="tw.Write(txt)";
_tw.Write(_txt);
 //BA.debugLineNum = 186;BA.debugLine="tw.Close";
_tw.Close();
 //BA.debugLineNum = 187;BA.debugLine="End Sub";
return "";
}
public static String  _savepath(anywheresoftware.b4a.BA _ba) throws Exception{
anywheresoftware.b4a.randomaccessfile.RandomAccessFile _randomfile = null;
 //BA.debugLineNum = 22;BA.debugLine="Sub SavePath";
 //BA.debugLineNum = 23;BA.debugLine="Dim RandomFile As RandomAccessFile";
_randomfile = new anywheresoftware.b4a.randomaccessfile.RandomAccessFile();
 //BA.debugLineNum = 25;BA.debugLine="RandomFile.Initialize(Main.GPSDir, Main.GPSPathFi";
_randomfile.Initialize(mostCurrent._main._gpsdir,mostCurrent._main._gpspathfilename,anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 26;BA.debugLine="RandomFile.WriteObject(Main.GPSPathComment, False";
_randomfile.WriteObject((Object)(mostCurrent._main._gpspathcomment),anywheresoftware.b4a.keywords.Common.False,_randomfile.CurrentPosition);
 //BA.debugLineNum = 27;BA.debugLine="RandomFile.WriteObject(Main.GPSPath, False, Rando";
_randomfile.WriteObject((Object)(mostCurrent._main._gpspath.getObject()),anywheresoftware.b4a.keywords.Common.False,_randomfile.CurrentPosition);
 //BA.debugLineNum = 28;BA.debugLine="RandomFile.Close";
_randomfile.Close();
 //BA.debugLineNum = 29;BA.debugLine="End Sub";
return "";
}
}
